# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="ry"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git django python gitfast golang)

source $ZSH/oh-my-zsh.sh

export CLIB=$HOME/workspace/clib
export LIB_CLIB=$HOME/workspace/clib/lib/libclib.a
export CPPLIB=$HOME/workspace/cpplib
export LIB_CPPLIB=$HOME/workspace/clib/lib/libcpplib.a
export PYTHONLIB=/home/ry/workspace/pythonlib
export SQLITE=/home/ry/workspace/sqlite-3.7.14
export SOCI=/home/ry/workspace/soci-3.1.0
alias ee='emacsclient -c'
alias j='jobs'
alias valgrind='valgrind --leak-check=full --show-reachable=yes'
#zlib evn

export ZLIB=$HOME/workspace/zlib-1.2.6
export LIB_ZLIB=$ZLIB/lib/libz_i686.a

export PCAP=$HOME/workspace/libpcap-1.3.0
export LIB_PCAP=$HOME/workspace/libpcap-1.3.0/libpcap.a

export BUILD_OUTPUT=/home/ry/tmp/python-demo/lib/
export SNIP=/home/ry/.vim/bundle/ultisnips/UltiSnips
export DOT=/home/ry/Documents/github/dotfile
# Customize to your needs...
# go lang relate
export GOROOT=$HOME/tmp/go/
export GOARCH=386
export GOOS=linux
export PATH=$PATH:/home/ry/tmp/go/bin

alias Ai='sudo apt-get install'
alias As='apt-cache search'
alias lcc='g++ -g -std=c++11'
alias f='find . -name '

alias -s c=gvim
alias -s h=gvim
alias -s cc=gvim
alias -s cpp=gvim
alias tmux='tmux -2'



