# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="gnzh"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git python gitfast docker-compose docker)

source $ZSH/oh-my-zsh.sh

alias ee='emacsclient -c'
alias j='jobs'
alias valgrind='valgrind --leak-check=full --show-reachable=yes'
#zlib evn

# Customize to your needs...

alias Ai='sudo apt-get install'
alias As='apt-cache search'
alias lcc='g++ -g -std=c++11'
alias f='find . -name '
alias u='source ~/.zshrc'

alias -s c=gvim
alias -s h=gvim
alias -s cc=gvim
alias -s cpp=gvim
alias tmux='tmux -2'
alias g='git status -sb'

export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin/
alias gb='go build'

if [ -n "$INSIDE_EMACS" ]; then
    export EDITOR=emacsclient
    unset zle_bracketed_paste  # This line
fi

#rust
export PATH=$HOME/.cabal/bin:/opt/cabal/1.24/bin:/opt/ghc/7.10.3/bin:$PATH:$HOME/.cargo/bin





alias wxdb='mycli -u huayun -h 172.16.78.10 -p fE6atQvtA6 neutron'
alias xmdb='mycli -u neutron -h 10.21.1.228 -p neutron'
alias ironic='mycli -h 172.16.28.20 -u admin -P 3306 -p 123456'
alias proxygoget='http_proxy=10.21.2.214:808 go get -v -u'
alias proxypush='http_proxy=10.21.2.214:808 git push'


# java
export JAVA_HOME=/usr/local/java
CLASSPATH=/usr/local/java/lib/dt.jar:/usr/local/java/lib/tools.jar
PATH=/usr/local/java/bin:$PATH
export PATH JAVA_HOME CLASSPATH

#FlameGraph
PATH=$PATH:/usr/local/FlameGraph
export PATH
